# Generated by Django 4.0.7 on 2022-08-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('music', models.FileField(upload_to='musics')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
