# Generated by Django 4.0.7 on 2022-08-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicPlayerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('music', models.FileField(upload_to='musics')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='MusicPlayer',
        ),
    ]
